version: '3.8'
services:
  camera_ctrler:
    container_name: camera_ctrler
    image: camera_ctrler
    build:
      context: ./
      dockerfile:  Dockerfile/cameractrlDockerfile
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./camera_100:/app
      - ./rtsp_test/frames:/app/image
    environment:
      - WORKER=3
      - SERVERIP=YOUR_SERVERIP
      - ACCOUNT=YOUR_ACCOUNT
      - PASSWORD=YOUR_PASSWORD
    ports:
      - "15439:5000"
    command: sh -c "flask run --no-debugger --host 0.0.0.0"
    
