version: '3.8'
services:
  httpobjectrecognition:
    container_name: http_object_recognition
    image: http_object_recognition
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile/httpobjectrecognitionDockerfile
    env_file:
      - path: docker_envs/httpobjectrecognition.env
        required: true
    volumes:
      - ./http_object_recognition:/app
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: python app.py


  camera_100:
    container_name: camera_100
    image: camera_100
    build:
      context: ./
      dockerfile:  Dockerfile/camera100Dockerfile
    stdin_open: true
    tty: true
    restart: always
    env_file: docker_envs/citynotify.env
    volumes:
      - ./camera_100:/app
      - ./rtsp_test/frames:/app/image
    ports:
      - "15439:5000"
    command: sh -c "flask run --no-debugger --host 0.0.0.0"
    